// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ContainerDelete(arg1:string):Promise<void>;

export function ContainerList():Promise<Array<main.Container>>;

export function ContainerStart(arg1:string):Promise<void>;

export function ContainerStop(arg1:string):Promise<void>;

export function ImageDelete(arg1:string):Promise<void>;

export function ImageList():Promise<Array<main.Image>>;
