// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ContainerDelete(arg1) {
  return window['go']['main']['App']['ContainerDelete'](arg1);
}

export function ContainerList() {
  return window['go']['main']['App']['ContainerList']();
}

export function ContainerStart(arg1) {
  return window['go']['main']['App']['ContainerStart'](arg1);
}

export function ContainerStop(arg1) {
  return window['go']['main']['App']['ContainerStop'](arg1);
}

export function ImageDelete(arg1) {
  return window['go']['main']['App']['ImageDelete'](arg1);
}

export function ImageList() {
  return window['go']['main']['App']['ImageList']();
}

export function Info() {
  return window['go']['main']['App']['Info']();
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function VolumeDelete(arg1) {
  return window['go']['main']['App']['VolumeDelete'](arg1);
}

export function VolumeList() {
  return window['go']['main']['App']['VolumeList']();
}
